# base image
FROM python:3.7.2-alpine

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

RUN pip3 install pipenv

# set working directory
WORKDIR /home/app

COPY Pipfile Pipfile.lock ./
RUN pipenv install --system --dev

COPY . /home/app

# run server
CMD ["/home/app/infra/run-worker-dev.sh"]
